/* 
 * ATG Store
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Pki.eBusiness.ErpApi.DataAccess.Client.SwaggerDateConverter;

namespace Pki.eBusiness.ErpApi.DataAccess.Model
{
    /// <summary>
    /// FavoritesCountDto
    /// </summary>
    [DataContract]
    public partial class FavoritesCountDto :  IEquatable<FavoritesCountDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FavoritesCountDto" /> class.
        /// </summary>
        /// <param name="FavoritesCount">FavoritesCount.</param>
        public FavoritesCountDto(int? FavoritesCount = default(int?))
        {
            this.FavoritesCount = FavoritesCount;
        }
        
        /// <summary>
        /// Gets or Sets FavoritesCount
        /// </summary>
        [DataMember(Name="favoritesCount", EmitDefaultValue=false)]
        public int? FavoritesCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FavoritesCountDto {\n");
            sb.Append("  FavoritesCount: ").Append(FavoritesCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FavoritesCountDto);
        }

        /// <summary>
        /// Returns true if FavoritesCountDto instances are equal
        /// </summary>
        /// <param name="input">Instance of FavoritesCountDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FavoritesCountDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FavoritesCount == input.FavoritesCount ||
                    (this.FavoritesCount != null &&
                    this.FavoritesCount.Equals(input.FavoritesCount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FavoritesCount != null)
                    hashCode = hashCode * 59 + this.FavoritesCount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
