/* 
 * ATG Store
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Pki.eBusiness.ErpApi.DataAccess.Client.SwaggerDateConverter;

namespace Pki.eBusiness.ErpApi.DataAccess.Model
{
    /// <summary>
    /// MiniCartDto
    /// </summary>
    [DataContract]
    public partial class MiniCartDto :  IEquatable<MiniCartDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MiniCartDto" /> class.
        /// </summary>
        /// <param name="Count">Count.</param>
        /// <param name="OrderSummary">OrderSummary.</param>
        /// <param name="LineItems">LineItems.</param>
        public MiniCartDto(int? Count = default(int?), MiniCartOrderPriceDto OrderSummary = default(MiniCartOrderPriceDto), List<MiniCartCommerceItemDto> LineItems = default(List<MiniCartCommerceItemDto>))
        {
            this.Count = Count;
            this.OrderSummary = OrderSummary;
            this.LineItems = LineItems;
        }
        
        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [DataMember(Name="count", EmitDefaultValue=false)]
        public int? Count { get; set; }

        /// <summary>
        /// Gets or Sets OrderSummary
        /// </summary>
        [DataMember(Name="orderSummary", EmitDefaultValue=false)]
        public MiniCartOrderPriceDto OrderSummary { get; set; }

        /// <summary>
        /// Gets or Sets LineItems
        /// </summary>
        [DataMember(Name="lineItems", EmitDefaultValue=false)]
        public List<MiniCartCommerceItemDto> LineItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MiniCartDto {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  OrderSummary: ").Append(OrderSummary).Append("\n");
            sb.Append("  LineItems: ").Append(LineItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MiniCartDto);
        }

        /// <summary>
        /// Returns true if MiniCartDto instances are equal
        /// </summary>
        /// <param name="input">Instance of MiniCartDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MiniCartDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Count == input.Count ||
                    (this.Count != null &&
                    this.Count.Equals(input.Count))
                ) && 
                (
                    this.OrderSummary == input.OrderSummary ||
                    (this.OrderSummary != null &&
                    this.OrderSummary.Equals(input.OrderSummary))
                ) && 
                (
                    this.LineItems == input.LineItems ||
                    this.LineItems != null &&
                    this.LineItems.SequenceEqual(input.LineItems)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Count != null)
                    hashCode = hashCode * 59 + this.Count.GetHashCode();
                if (this.OrderSummary != null)
                    hashCode = hashCode * 59 + this.OrderSummary.GetHashCode();
                if (this.LineItems != null)
                    hashCode = hashCode * 59 + this.LineItems.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
