/* 
 * eCommerce
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Pki.eBusiness.ErpApi.DataAccess.ErpApi.Model
{
    /// <summary>
    /// SimulateOrderResponseRootBILLINGPARTY
    /// </summary>
    
    public partial class SimulateOrderResponseRootBILLINGPARTY :  IEquatable<SimulateOrderResponseRootBILLINGPARTY>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SimulateOrderResponseRootBILLINGPARTY" /> class.
        /// </summary>
        /// <param name="PAYER">PAYER.</param>
        /// <param name="NAME">NAME.</param>
        /// <param name="STREET">STREET.</param>
        /// <param name="PO_BOX">PO_BOX.</param>
        /// <param name="POSTL_CODE">POSTL_CODE.</param>
        /// <param name="POBX_PCD">POBX_PCD.</param>
        /// <param name="CITY">CITY.</param>
        /// <param name="LANGU">LANGU.</param>
        /// <param name="COUNTRY">COUNTRY.</param>
        /// <param name="TELEPHONE">TELEPHONE.</param>
        /// <param name="C_CTR_AREA">C_CTR_AREA.</param>
        /// <param name="CRED_ACCNT">CRED_ACCNT.</param>
        /// <param name="CRED_LIMIT">CRED_LIMIT.</param>
        /// <param name="ORDER_VALS">ORDER_VALS.</param>
        /// <param name="RCVBL_VALS">RCVBL_VALS.</param>
        /// <param name="CRED_LIAB">CRED_LIAB.</param>
        /// <param name="CURRENCY">CURRENCY.</param>
        /// <param name="MN_INVOICE">MN_INVOICE.</param>
        /// <param name="BILL_SCHED">BILL_SCHED.</param>
        /// <param name="LIST_SCHED">LIST_SCHED.</param>
        /// <param name="VAL_LIMIT">VAL_LIMIT.</param>
        /// <param name="ACCNT_ASGN">ACCNT_ASGN.</param>
        /// <param name="PMNTTRMS">PMNTTRMS.</param>
        /// <param name="ADD_VAL_DY">ADD_VAL_DY.</param>
        /// <param name="FIX_VAL_DY">FIX_VAL_DY.</param>
        /// <param name="PROD_PROP">PROD_PROP.</param>
        /// <param name="BILL_BLOCK">BILL_BLOCK.</param>
        /// <param name="ORDER_BLCK">ORDER_BLCK.</param>
        /// <param name="VAT_REG_NO">VAT_REG_NO.</param>
        /// <param name="VAT_CNTRY">VAT_CNTRY.</param>
        /// <param name="TAXCLASS1">TAXCLASS1.</param>
        /// <param name="TAXCLASS2">TAXCLASS2.</param>
        /// <param name="TAXCLASS3">TAXCLASS3.</param>
        /// <param name="TAXCLASS4">TAXCLASS4.</param>
        /// <param name="TAXCLASS5">TAXCLASS5.</param>
        /// <param name="TAXCLASS6">TAXCLASS6.</param>
        /// <param name="TAXCLASS7">TAXCLASS7.</param>
        /// <param name="TAXCLASS8">TAXCLASS8.</param>
        /// <param name="TAXCLASS9">TAXCLASS9.</param>
        /// <param name="REBATE_REL">REBATE_REL.</param>
        /// <param name="REBATE_FRM">REBATE_FRM.</param>
        /// <param name="CRED_GROUP">CRED_GROUP.</param>
        /// <param name="REPR_GROUP">REPR_GROUP.</param>
        /// <param name="RISK_CATEG">RISK_CATEG.</param>
        /// <param name="TRADE_ID">TRADE_ID.</param>
        public SimulateOrderResponseRootBILLINGPARTY(string PAYER = default(string), string NAME = default(string), string STREET = default(string), string PO_BOX = default(string), string POSTL_CODE = default(string), string POBX_PCD = default(string), string CITY = default(string), string LANGU = default(string), string COUNTRY = default(string), string TELEPHONE = default(string), string C_CTR_AREA = default(string), string CRED_ACCNT = default(string), string CRED_LIMIT = default(string), string ORDER_VALS = default(string), string RCVBL_VALS = default(string), string CRED_LIAB = default(string), string CURRENCY = default(string), string MN_INVOICE = default(string), string BILL_SCHED = default(string), string LIST_SCHED = default(string), string VAL_LIMIT = default(string), string ACCNT_ASGN = default(string), string PMNTTRMS = default(string), string ADD_VAL_DY = default(string), string FIX_VAL_DY = default(string), string PROD_PROP = default(string), string BILL_BLOCK = default(string), string ORDER_BLCK = default(string), string VAT_REG_NO = default(string), string VAT_CNTRY = default(string), string TAXCLASS1 = default(string), string TAXCLASS2 = default(string), string TAXCLASS3 = default(string), string TAXCLASS4 = default(string), string TAXCLASS5 = default(string), string TAXCLASS6 = default(string), string TAXCLASS7 = default(string), string TAXCLASS8 = default(string), string TAXCLASS9 = default(string), string REBATE_REL = default(string), string REBATE_FRM = default(string), string CRED_GROUP = default(string), string REPR_GROUP = default(string), string RISK_CATEG = default(string), string TRADE_ID = default(string))
        {
            this.PAYER = PAYER;
            this.NAME = NAME;
            this.STREET = STREET;
            this.PO_BOX = PO_BOX;
            this.POSTL_CODE = POSTL_CODE;
            this.POBX_PCD = POBX_PCD;
            this.CITY = CITY;
            this.LANGU = LANGU;
            this.COUNTRY = COUNTRY;
            this.TELEPHONE = TELEPHONE;
            this.C_CTR_AREA = C_CTR_AREA;
            this.CRED_ACCNT = CRED_ACCNT;
            this.CRED_LIMIT = CRED_LIMIT;
            this.ORDER_VALS = ORDER_VALS;
            this.RCVBL_VALS = RCVBL_VALS;
            this.CRED_LIAB = CRED_LIAB;
            this.CURRENCY = CURRENCY;
            this.MN_INVOICE = MN_INVOICE;
            this.BILL_SCHED = BILL_SCHED;
            this.LIST_SCHED = LIST_SCHED;
            this.VAL_LIMIT = VAL_LIMIT;
            this.ACCNT_ASGN = ACCNT_ASGN;
            this.PMNTTRMS = PMNTTRMS;
            this.ADD_VAL_DY = ADD_VAL_DY;
            this.FIX_VAL_DY = FIX_VAL_DY;
            this.PROD_PROP = PROD_PROP;
            this.BILL_BLOCK = BILL_BLOCK;
            this.ORDER_BLCK = ORDER_BLCK;
            this.VAT_REG_NO = VAT_REG_NO;
            this.VAT_CNTRY = VAT_CNTRY;
            this.TAXCLASS1 = TAXCLASS1;
            this.TAXCLASS2 = TAXCLASS2;
            this.TAXCLASS3 = TAXCLASS3;
            this.TAXCLASS4 = TAXCLASS4;
            this.TAXCLASS5 = TAXCLASS5;
            this.TAXCLASS6 = TAXCLASS6;
            this.TAXCLASS7 = TAXCLASS7;
            this.TAXCLASS8 = TAXCLASS8;
            this.TAXCLASS9 = TAXCLASS9;
            this.REBATE_REL = REBATE_REL;
            this.REBATE_FRM = REBATE_FRM;
            this.CRED_GROUP = CRED_GROUP;
            this.REPR_GROUP = REPR_GROUP;
            this.RISK_CATEG = RISK_CATEG;
            this.TRADE_ID = TRADE_ID;
        }
        
        /// <summary>
        /// Gets or Sets PAYER
        /// </summary>
        [DataMember(Name="PAYER", EmitDefaultValue=false)]
        public string PAYER { get; set; }

        /// <summary>
        /// Gets or Sets NAME
        /// </summary>
        [DataMember(Name="NAME", EmitDefaultValue=false)]
        public string NAME { get; set; }

        /// <summary>
        /// Gets or Sets STREET
        /// </summary>
        [DataMember(Name="STREET", EmitDefaultValue=false)]
        public string STREET { get; set; }

        /// <summary>
        /// Gets or Sets PO_BOX
        /// </summary>
        [DataMember(Name="PO_BOX", EmitDefaultValue=false)]
        public string PO_BOX { get; set; }

        /// <summary>
        /// Gets or Sets POSTL_CODE
        /// </summary>
        [DataMember(Name="POSTL_CODE", EmitDefaultValue=false)]
        public string POSTL_CODE { get; set; }

        /// <summary>
        /// Gets or Sets POBX_PCD
        /// </summary>
        [DataMember(Name="POBX_PCD", EmitDefaultValue=false)]
        public string POBX_PCD { get; set; }

        /// <summary>
        /// Gets or Sets CITY
        /// </summary>
        [DataMember(Name="CITY", EmitDefaultValue=false)]
        public string CITY { get; set; }

        /// <summary>
        /// Gets or Sets LANGU
        /// </summary>
        [DataMember(Name="LANGU", EmitDefaultValue=false)]
        public string LANGU { get; set; }

        /// <summary>
        /// Gets or Sets COUNTRY
        /// </summary>
        [DataMember(Name="COUNTRY", EmitDefaultValue=false)]
        public string COUNTRY { get; set; }

        /// <summary>
        /// Gets or Sets TELEPHONE
        /// </summary>
        [DataMember(Name="TELEPHONE", EmitDefaultValue=false)]
        public string TELEPHONE { get; set; }

        /// <summary>
        /// Gets or Sets C_CTR_AREA
        /// </summary>
        [DataMember(Name="C_CTR_AREA", EmitDefaultValue=false)]
        public string C_CTR_AREA { get; set; }

        /// <summary>
        /// Gets or Sets CRED_ACCNT
        /// </summary>
        [DataMember(Name="CRED_ACCNT", EmitDefaultValue=false)]
        public string CRED_ACCNT { get; set; }

        /// <summary>
        /// Gets or Sets CRED_LIMIT
        /// </summary>
        [DataMember(Name="CRED_LIMIT", EmitDefaultValue=false)]
        public string CRED_LIMIT { get; set; }

        /// <summary>
        /// Gets or Sets ORDER_VALS
        /// </summary>
        [DataMember(Name="ORDER_VALS", EmitDefaultValue=false)]
        public string ORDER_VALS { get; set; }

        /// <summary>
        /// Gets or Sets RCVBL_VALS
        /// </summary>
        [DataMember(Name="RCVBL_VALS", EmitDefaultValue=false)]
        public string RCVBL_VALS { get; set; }

        /// <summary>
        /// Gets or Sets CRED_LIAB
        /// </summary>
        [DataMember(Name="CRED_LIAB", EmitDefaultValue=false)]
        public string CRED_LIAB { get; set; }

        /// <summary>
        /// Gets or Sets CURRENCY
        /// </summary>
        [DataMember(Name="CURRENCY", EmitDefaultValue=false)]
        public string CURRENCY { get; set; }

        /// <summary>
        /// Gets or Sets MN_INVOICE
        /// </summary>
        [DataMember(Name="MN_INVOICE", EmitDefaultValue=false)]
        public string MN_INVOICE { get; set; }

        /// <summary>
        /// Gets or Sets BILL_SCHED
        /// </summary>
        [DataMember(Name="BILL_SCHED", EmitDefaultValue=false)]
        public string BILL_SCHED { get; set; }

        /// <summary>
        /// Gets or Sets LIST_SCHED
        /// </summary>
        [DataMember(Name="LIST_SCHED", EmitDefaultValue=false)]
        public string LIST_SCHED { get; set; }

        /// <summary>
        /// Gets or Sets VAL_LIMIT
        /// </summary>
        [DataMember(Name="VAL_LIMIT", EmitDefaultValue=false)]
        public string VAL_LIMIT { get; set; }

        /// <summary>
        /// Gets or Sets ACCNT_ASGN
        /// </summary>
        [DataMember(Name="ACCNT_ASGN", EmitDefaultValue=false)]
        public string ACCNT_ASGN { get; set; }

        /// <summary>
        /// Gets or Sets PMNTTRMS
        /// </summary>
        [DataMember(Name="PMNTTRMS", EmitDefaultValue=false)]
        public string PMNTTRMS { get; set; }

        /// <summary>
        /// Gets or Sets ADD_VAL_DY
        /// </summary>
        [DataMember(Name="ADD_VAL_DY", EmitDefaultValue=false)]
        public string ADD_VAL_DY { get; set; }

        /// <summary>
        /// Gets or Sets FIX_VAL_DY
        /// </summary>
        [DataMember(Name="FIX_VAL_DY", EmitDefaultValue=false)]
        public string FIX_VAL_DY { get; set; }

        /// <summary>
        /// Gets or Sets PROD_PROP
        /// </summary>
        [DataMember(Name="PROD_PROP", EmitDefaultValue=false)]
        public string PROD_PROP { get; set; }

        /// <summary>
        /// Gets or Sets BILL_BLOCK
        /// </summary>
        [DataMember(Name="BILL_BLOCK", EmitDefaultValue=false)]
        public string BILL_BLOCK { get; set; }

        /// <summary>
        /// Gets or Sets ORDER_BLCK
        /// </summary>
        [DataMember(Name="ORDER_BLCK", EmitDefaultValue=false)]
        public string ORDER_BLCK { get; set; }

        /// <summary>
        /// Gets or Sets VAT_REG_NO
        /// </summary>
        [DataMember(Name="VAT_REG_NO", EmitDefaultValue=false)]
        public string VAT_REG_NO { get; set; }

        /// <summary>
        /// Gets or Sets VAT_CNTRY
        /// </summary>
        [DataMember(Name="VAT_CNTRY", EmitDefaultValue=false)]
        public string VAT_CNTRY { get; set; }

        /// <summary>
        /// Gets or Sets TAXCLASS1
        /// </summary>
        [DataMember(Name="TAX_CLASS1", EmitDefaultValue=false)]
        public string TAXCLASS1 { get; set; }

        /// <summary>
        /// Gets or Sets TAXCLASS2
        /// </summary>
        [DataMember(Name="TAX_CLASS2", EmitDefaultValue=false)]
        public string TAXCLASS2 { get; set; }

        /// <summary>
        /// Gets or Sets TAXCLASS3
        /// </summary>
        [DataMember(Name="TAX_CLASS3", EmitDefaultValue=false)]
        public string TAXCLASS3 { get; set; }

        /// <summary>
        /// Gets or Sets TAXCLASS4
        /// </summary>
        [DataMember(Name="TAX_CLASS4", EmitDefaultValue=false)]
        public string TAXCLASS4 { get; set; }

        /// <summary>
        /// Gets or Sets TAXCLASS5
        /// </summary>
        [DataMember(Name="TAX_CLASS5", EmitDefaultValue=false)]
        public string TAXCLASS5 { get; set; }

        /// <summary>
        /// Gets or Sets TAXCLASS6
        /// </summary>
        [DataMember(Name="TAX_CLASS6", EmitDefaultValue=false)]
        public string TAXCLASS6 { get; set; }

        /// <summary>
        /// Gets or Sets TAXCLASS7
        /// </summary>
        [DataMember(Name="TAX_CLASS7", EmitDefaultValue=false)]
        public string TAXCLASS7 { get; set; }

        /// <summary>
        /// Gets or Sets TAXCLASS8
        /// </summary>
        [DataMember(Name="TAX_CLASS8", EmitDefaultValue=false)]
        public string TAXCLASS8 { get; set; }

        /// <summary>
        /// Gets or Sets TAXCLASS9
        /// </summary>
        [DataMember(Name="TAX_CLASS9", EmitDefaultValue=false)]
        public string TAXCLASS9 { get; set; }

        /// <summary>
        /// Gets or Sets REBATE_REL
        /// </summary>
        [DataMember(Name="REBATE_REL", EmitDefaultValue=false)]
        public string REBATE_REL { get; set; }

        /// <summary>
        /// Gets or Sets REBATE_FRM
        /// </summary>
        [DataMember(Name="REBATE_FRM", EmitDefaultValue=false)]
        public string REBATE_FRM { get; set; }

        /// <summary>
        /// Gets or Sets CRED_GROUP
        /// </summary>
        [DataMember(Name="CRED_GROUP", EmitDefaultValue=false)]
        public string CRED_GROUP { get; set; }

        /// <summary>
        /// Gets or Sets REPR_GROUP
        /// </summary>
        [DataMember(Name="REPR_GROUP", EmitDefaultValue=false)]
        public string REPR_GROUP { get; set; }

        /// <summary>
        /// Gets or Sets RISK_CATEG
        /// </summary>
        [DataMember(Name="RISK_CATEG", EmitDefaultValue=false)]
        public string RISK_CATEG { get; set; }

        /// <summary>
        /// Gets or Sets TRADE_ID
        /// </summary>
        [DataMember(Name="TRADE_ID", EmitDefaultValue=false)]
        public string TRADE_ID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SimulateOrderResponseRootBILLINGPARTY {\n");
            sb.Append("  PAYER: ").Append(PAYER).Append("\n");
            sb.Append("  NAME: ").Append(NAME).Append("\n");
            sb.Append("  STREET: ").Append(STREET).Append("\n");
            sb.Append("  PO_BOX: ").Append(PO_BOX).Append("\n");
            sb.Append("  POSTL_CODE: ").Append(POSTL_CODE).Append("\n");
            sb.Append("  POBX_PCD: ").Append(POBX_PCD).Append("\n");
            sb.Append("  CITY: ").Append(CITY).Append("\n");
            sb.Append("  LANGU: ").Append(LANGU).Append("\n");
            sb.Append("  COUNTRY: ").Append(COUNTRY).Append("\n");
            sb.Append("  TELEPHONE: ").Append(TELEPHONE).Append("\n");
            sb.Append("  C_CTR_AREA: ").Append(C_CTR_AREA).Append("\n");
            sb.Append("  CRED_ACCNT: ").Append(CRED_ACCNT).Append("\n");
            sb.Append("  CRED_LIMIT: ").Append(CRED_LIMIT).Append("\n");
            sb.Append("  ORDER_VALS: ").Append(ORDER_VALS).Append("\n");
            sb.Append("  RCVBL_VALS: ").Append(RCVBL_VALS).Append("\n");
            sb.Append("  CRED_LIAB: ").Append(CRED_LIAB).Append("\n");
            sb.Append("  CURRENCY: ").Append(CURRENCY).Append("\n");
            sb.Append("  MN_INVOICE: ").Append(MN_INVOICE).Append("\n");
            sb.Append("  BILL_SCHED: ").Append(BILL_SCHED).Append("\n");
            sb.Append("  LIST_SCHED: ").Append(LIST_SCHED).Append("\n");
            sb.Append("  VAL_LIMIT: ").Append(VAL_LIMIT).Append("\n");
            sb.Append("  ACCNT_ASGN: ").Append(ACCNT_ASGN).Append("\n");
            sb.Append("  PMNTTRMS: ").Append(PMNTTRMS).Append("\n");
            sb.Append("  ADD_VAL_DY: ").Append(ADD_VAL_DY).Append("\n");
            sb.Append("  FIX_VAL_DY: ").Append(FIX_VAL_DY).Append("\n");
            sb.Append("  PROD_PROP: ").Append(PROD_PROP).Append("\n");
            sb.Append("  BILL_BLOCK: ").Append(BILL_BLOCK).Append("\n");
            sb.Append("  ORDER_BLCK: ").Append(ORDER_BLCK).Append("\n");
            sb.Append("  VAT_REG_NO: ").Append(VAT_REG_NO).Append("\n");
            sb.Append("  VAT_CNTRY: ").Append(VAT_CNTRY).Append("\n");
            sb.Append("  TAXCLASS1: ").Append(TAXCLASS1).Append("\n");
            sb.Append("  TAXCLASS2: ").Append(TAXCLASS2).Append("\n");
            sb.Append("  TAXCLASS3: ").Append(TAXCLASS3).Append("\n");
            sb.Append("  TAXCLASS4: ").Append(TAXCLASS4).Append("\n");
            sb.Append("  TAXCLASS5: ").Append(TAXCLASS5).Append("\n");
            sb.Append("  TAXCLASS6: ").Append(TAXCLASS6).Append("\n");
            sb.Append("  TAXCLASS7: ").Append(TAXCLASS7).Append("\n");
            sb.Append("  TAXCLASS8: ").Append(TAXCLASS8).Append("\n");
            sb.Append("  TAXCLASS9: ").Append(TAXCLASS9).Append("\n");
            sb.Append("  REBATE_REL: ").Append(REBATE_REL).Append("\n");
            sb.Append("  REBATE_FRM: ").Append(REBATE_FRM).Append("\n");
            sb.Append("  CRED_GROUP: ").Append(CRED_GROUP).Append("\n");
            sb.Append("  REPR_GROUP: ").Append(REPR_GROUP).Append("\n");
            sb.Append("  RISK_CATEG: ").Append(RISK_CATEG).Append("\n");
            sb.Append("  TRADE_ID: ").Append(TRADE_ID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SimulateOrderResponseRootBILLINGPARTY);
        }

        /// <summary>
        /// Returns true if SimulateOrderResponseRootBILLINGPARTY instances are equal
        /// </summary>
        /// <param name="input">Instance of SimulateOrderResponseRootBILLINGPARTY to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SimulateOrderResponseRootBILLINGPARTY input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PAYER == input.PAYER ||
                    (this.PAYER != null &&
                    this.PAYER.Equals(input.PAYER))
                ) && 
                (
                    this.NAME == input.NAME ||
                    (this.NAME != null &&
                    this.NAME.Equals(input.NAME))
                ) && 
                (
                    this.STREET == input.STREET ||
                    (this.STREET != null &&
                    this.STREET.Equals(input.STREET))
                ) && 
                (
                    this.PO_BOX == input.PO_BOX ||
                    (this.PO_BOX != null &&
                    this.PO_BOX.Equals(input.PO_BOX))
                ) && 
                (
                    this.POSTL_CODE == input.POSTL_CODE ||
                    (this.POSTL_CODE != null &&
                    this.POSTL_CODE.Equals(input.POSTL_CODE))
                ) && 
                (
                    this.POBX_PCD == input.POBX_PCD ||
                    (this.POBX_PCD != null &&
                    this.POBX_PCD.Equals(input.POBX_PCD))
                ) && 
                (
                    this.CITY == input.CITY ||
                    (this.CITY != null &&
                    this.CITY.Equals(input.CITY))
                ) && 
                (
                    this.LANGU == input.LANGU ||
                    (this.LANGU != null &&
                    this.LANGU.Equals(input.LANGU))
                ) && 
                (
                    this.COUNTRY == input.COUNTRY ||
                    (this.COUNTRY != null &&
                    this.COUNTRY.Equals(input.COUNTRY))
                ) && 
                (
                    this.TELEPHONE == input.TELEPHONE ||
                    (this.TELEPHONE != null &&
                    this.TELEPHONE.Equals(input.TELEPHONE))
                ) && 
                (
                    this.C_CTR_AREA == input.C_CTR_AREA ||
                    (this.C_CTR_AREA != null &&
                    this.C_CTR_AREA.Equals(input.C_CTR_AREA))
                ) && 
                (
                    this.CRED_ACCNT == input.CRED_ACCNT ||
                    (this.CRED_ACCNT != null &&
                    this.CRED_ACCNT.Equals(input.CRED_ACCNT))
                ) && 
                (
                    this.CRED_LIMIT == input.CRED_LIMIT ||
                    (this.CRED_LIMIT != null &&
                    this.CRED_LIMIT.Equals(input.CRED_LIMIT))
                ) && 
                (
                    this.ORDER_VALS == input.ORDER_VALS ||
                    (this.ORDER_VALS != null &&
                    this.ORDER_VALS.Equals(input.ORDER_VALS))
                ) && 
                (
                    this.RCVBL_VALS == input.RCVBL_VALS ||
                    (this.RCVBL_VALS != null &&
                    this.RCVBL_VALS.Equals(input.RCVBL_VALS))
                ) && 
                (
                    this.CRED_LIAB == input.CRED_LIAB ||
                    (this.CRED_LIAB != null &&
                    this.CRED_LIAB.Equals(input.CRED_LIAB))
                ) && 
                (
                    this.CURRENCY == input.CURRENCY ||
                    (this.CURRENCY != null &&
                    this.CURRENCY.Equals(input.CURRENCY))
                ) && 
                (
                    this.MN_INVOICE == input.MN_INVOICE ||
                    (this.MN_INVOICE != null &&
                    this.MN_INVOICE.Equals(input.MN_INVOICE))
                ) && 
                (
                    this.BILL_SCHED == input.BILL_SCHED ||
                    (this.BILL_SCHED != null &&
                    this.BILL_SCHED.Equals(input.BILL_SCHED))
                ) && 
                (
                    this.LIST_SCHED == input.LIST_SCHED ||
                    (this.LIST_SCHED != null &&
                    this.LIST_SCHED.Equals(input.LIST_SCHED))
                ) && 
                (
                    this.VAL_LIMIT == input.VAL_LIMIT ||
                    (this.VAL_LIMIT != null &&
                    this.VAL_LIMIT.Equals(input.VAL_LIMIT))
                ) && 
                (
                    this.ACCNT_ASGN == input.ACCNT_ASGN ||
                    (this.ACCNT_ASGN != null &&
                    this.ACCNT_ASGN.Equals(input.ACCNT_ASGN))
                ) && 
                (
                    this.PMNTTRMS == input.PMNTTRMS ||
                    (this.PMNTTRMS != null &&
                    this.PMNTTRMS.Equals(input.PMNTTRMS))
                ) && 
                (
                    this.ADD_VAL_DY == input.ADD_VAL_DY ||
                    (this.ADD_VAL_DY != null &&
                    this.ADD_VAL_DY.Equals(input.ADD_VAL_DY))
                ) && 
                (
                    this.FIX_VAL_DY == input.FIX_VAL_DY ||
                    (this.FIX_VAL_DY != null &&
                    this.FIX_VAL_DY.Equals(input.FIX_VAL_DY))
                ) && 
                (
                    this.PROD_PROP == input.PROD_PROP ||
                    (this.PROD_PROP != null &&
                    this.PROD_PROP.Equals(input.PROD_PROP))
                ) && 
                (
                    this.BILL_BLOCK == input.BILL_BLOCK ||
                    (this.BILL_BLOCK != null &&
                    this.BILL_BLOCK.Equals(input.BILL_BLOCK))
                ) && 
                (
                    this.ORDER_BLCK == input.ORDER_BLCK ||
                    (this.ORDER_BLCK != null &&
                    this.ORDER_BLCK.Equals(input.ORDER_BLCK))
                ) && 
                (
                    this.VAT_REG_NO == input.VAT_REG_NO ||
                    (this.VAT_REG_NO != null &&
                    this.VAT_REG_NO.Equals(input.VAT_REG_NO))
                ) && 
                (
                    this.VAT_CNTRY == input.VAT_CNTRY ||
                    (this.VAT_CNTRY != null &&
                    this.VAT_CNTRY.Equals(input.VAT_CNTRY))
                ) && 
                (
                    this.TAXCLASS1 == input.TAXCLASS1 ||
                    (this.TAXCLASS1 != null &&
                    this.TAXCLASS1.Equals(input.TAXCLASS1))
                ) && 
                (
                    this.TAXCLASS2 == input.TAXCLASS2 ||
                    (this.TAXCLASS2 != null &&
                    this.TAXCLASS2.Equals(input.TAXCLASS2))
                ) && 
                (
                    this.TAXCLASS3 == input.TAXCLASS3 ||
                    (this.TAXCLASS3 != null &&
                    this.TAXCLASS3.Equals(input.TAXCLASS3))
                ) && 
                (
                    this.TAXCLASS4 == input.TAXCLASS4 ||
                    (this.TAXCLASS4 != null &&
                    this.TAXCLASS4.Equals(input.TAXCLASS4))
                ) && 
                (
                    this.TAXCLASS5 == input.TAXCLASS5 ||
                    (this.TAXCLASS5 != null &&
                    this.TAXCLASS5.Equals(input.TAXCLASS5))
                ) && 
                (
                    this.TAXCLASS6 == input.TAXCLASS6 ||
                    (this.TAXCLASS6 != null &&
                    this.TAXCLASS6.Equals(input.TAXCLASS6))
                ) && 
                (
                    this.TAXCLASS7 == input.TAXCLASS7 ||
                    (this.TAXCLASS7 != null &&
                    this.TAXCLASS7.Equals(input.TAXCLASS7))
                ) && 
                (
                    this.TAXCLASS8 == input.TAXCLASS8 ||
                    (this.TAXCLASS8 != null &&
                    this.TAXCLASS8.Equals(input.TAXCLASS8))
                ) && 
                (
                    this.TAXCLASS9 == input.TAXCLASS9 ||
                    (this.TAXCLASS9 != null &&
                    this.TAXCLASS9.Equals(input.TAXCLASS9))
                ) && 
                (
                    this.REBATE_REL == input.REBATE_REL ||
                    (this.REBATE_REL != null &&
                    this.REBATE_REL.Equals(input.REBATE_REL))
                ) && 
                (
                    this.REBATE_FRM == input.REBATE_FRM ||
                    (this.REBATE_FRM != null &&
                    this.REBATE_FRM.Equals(input.REBATE_FRM))
                ) && 
                (
                    this.CRED_GROUP == input.CRED_GROUP ||
                    (this.CRED_GROUP != null &&
                    this.CRED_GROUP.Equals(input.CRED_GROUP))
                ) && 
                (
                    this.REPR_GROUP == input.REPR_GROUP ||
                    (this.REPR_GROUP != null &&
                    this.REPR_GROUP.Equals(input.REPR_GROUP))
                ) && 
                (
                    this.RISK_CATEG == input.RISK_CATEG ||
                    (this.RISK_CATEG != null &&
                    this.RISK_CATEG.Equals(input.RISK_CATEG))
                ) && 
                (
                    this.TRADE_ID == input.TRADE_ID ||
                    (this.TRADE_ID != null &&
                    this.TRADE_ID.Equals(input.TRADE_ID))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PAYER != null)
                    hashCode = hashCode * 59 + this.PAYER.GetHashCode();
                if (this.NAME != null)
                    hashCode = hashCode * 59 + this.NAME.GetHashCode();
                if (this.STREET != null)
                    hashCode = hashCode * 59 + this.STREET.GetHashCode();
                if (this.PO_BOX != null)
                    hashCode = hashCode * 59 + this.PO_BOX.GetHashCode();
                if (this.POSTL_CODE != null)
                    hashCode = hashCode * 59 + this.POSTL_CODE.GetHashCode();
                if (this.POBX_PCD != null)
                    hashCode = hashCode * 59 + this.POBX_PCD.GetHashCode();
                if (this.CITY != null)
                    hashCode = hashCode * 59 + this.CITY.GetHashCode();
                if (this.LANGU != null)
                    hashCode = hashCode * 59 + this.LANGU.GetHashCode();
                if (this.COUNTRY != null)
                    hashCode = hashCode * 59 + this.COUNTRY.GetHashCode();
                if (this.TELEPHONE != null)
                    hashCode = hashCode * 59 + this.TELEPHONE.GetHashCode();
                if (this.C_CTR_AREA != null)
                    hashCode = hashCode * 59 + this.C_CTR_AREA.GetHashCode();
                if (this.CRED_ACCNT != null)
                    hashCode = hashCode * 59 + this.CRED_ACCNT.GetHashCode();
                if (this.CRED_LIMIT != null)
                    hashCode = hashCode * 59 + this.CRED_LIMIT.GetHashCode();
                if (this.ORDER_VALS != null)
                    hashCode = hashCode * 59 + this.ORDER_VALS.GetHashCode();
                if (this.RCVBL_VALS != null)
                    hashCode = hashCode * 59 + this.RCVBL_VALS.GetHashCode();
                if (this.CRED_LIAB != null)
                    hashCode = hashCode * 59 + this.CRED_LIAB.GetHashCode();
                if (this.CURRENCY != null)
                    hashCode = hashCode * 59 + this.CURRENCY.GetHashCode();
                if (this.MN_INVOICE != null)
                    hashCode = hashCode * 59 + this.MN_INVOICE.GetHashCode();
                if (this.BILL_SCHED != null)
                    hashCode = hashCode * 59 + this.BILL_SCHED.GetHashCode();
                if (this.LIST_SCHED != null)
                    hashCode = hashCode * 59 + this.LIST_SCHED.GetHashCode();
                if (this.VAL_LIMIT != null)
                    hashCode = hashCode * 59 + this.VAL_LIMIT.GetHashCode();
                if (this.ACCNT_ASGN != null)
                    hashCode = hashCode * 59 + this.ACCNT_ASGN.GetHashCode();
                if (this.PMNTTRMS != null)
                    hashCode = hashCode * 59 + this.PMNTTRMS.GetHashCode();
                if (this.ADD_VAL_DY != null)
                    hashCode = hashCode * 59 + this.ADD_VAL_DY.GetHashCode();
                if (this.FIX_VAL_DY != null)
                    hashCode = hashCode * 59 + this.FIX_VAL_DY.GetHashCode();
                if (this.PROD_PROP != null)
                    hashCode = hashCode * 59 + this.PROD_PROP.GetHashCode();
                if (this.BILL_BLOCK != null)
                    hashCode = hashCode * 59 + this.BILL_BLOCK.GetHashCode();
                if (this.ORDER_BLCK != null)
                    hashCode = hashCode * 59 + this.ORDER_BLCK.GetHashCode();
                if (this.VAT_REG_NO != null)
                    hashCode = hashCode * 59 + this.VAT_REG_NO.GetHashCode();
                if (this.VAT_CNTRY != null)
                    hashCode = hashCode * 59 + this.VAT_CNTRY.GetHashCode();
                if (this.TAXCLASS1 != null)
                    hashCode = hashCode * 59 + this.TAXCLASS1.GetHashCode();
                if (this.TAXCLASS2 != null)
                    hashCode = hashCode * 59 + this.TAXCLASS2.GetHashCode();
                if (this.TAXCLASS3 != null)
                    hashCode = hashCode * 59 + this.TAXCLASS3.GetHashCode();
                if (this.TAXCLASS4 != null)
                    hashCode = hashCode * 59 + this.TAXCLASS4.GetHashCode();
                if (this.TAXCLASS5 != null)
                    hashCode = hashCode * 59 + this.TAXCLASS5.GetHashCode();
                if (this.TAXCLASS6 != null)
                    hashCode = hashCode * 59 + this.TAXCLASS6.GetHashCode();
                if (this.TAXCLASS7 != null)
                    hashCode = hashCode * 59 + this.TAXCLASS7.GetHashCode();
                if (this.TAXCLASS8 != null)
                    hashCode = hashCode * 59 + this.TAXCLASS8.GetHashCode();
                if (this.TAXCLASS9 != null)
                    hashCode = hashCode * 59 + this.TAXCLASS9.GetHashCode();
                if (this.REBATE_REL != null)
                    hashCode = hashCode * 59 + this.REBATE_REL.GetHashCode();
                if (this.REBATE_FRM != null)
                    hashCode = hashCode * 59 + this.REBATE_FRM.GetHashCode();
                if (this.CRED_GROUP != null)
                    hashCode = hashCode * 59 + this.CRED_GROUP.GetHashCode();
                if (this.REPR_GROUP != null)
                    hashCode = hashCode * 59 + this.REPR_GROUP.GetHashCode();
                if (this.RISK_CATEG != null)
                    hashCode = hashCode * 59 + this.RISK_CATEG.GetHashCode();
                if (this.TRADE_ID != null)
                    hashCode = hashCode * 59 + this.TRADE_ID.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
